version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro  # ro is for read-only. Ensures files can only be changed on local and not in container
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30        
  postgres:
    image: postgres
    environment:
        # default user is postgres. This will set the password for the that user with superuser privileges. 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi # this will be the default database
    volumes:
      - postgres-db:/var/lib/postgresql/data # where data is stored on the container
  # alembic:
  #   build: .
  #   command: alembic upgrade head
  #   environment:
  #     - DATABASE_HOSTNAME=postgres
  #     - DATABASE_PORT=5432
  #     - DATABASE_PASSWORD=postgres
  #     - DATABASE_NAME=fastapi
  #     - DATABASE_USERNAME=postgres
  #   depends_on:
  #     - postgres
volumes:
  postgres-db:





